version: '3.9'

services:

  db:
    image: postgres
    container_name: db_postgres
    restart: always
    
    environment:
      POSTGRES_PASSWORD: MalthusRonaldo
      POSTGRES_USER: Malthus
      POSTGRES_DB: tokens

    ports:
      - "5432:5432"

    volumes:
      - db_volume:/var/lib/postgresql/data


  adminer:
    image: adminer
    container_name: db_adminer
    restart: always
    ports:
      - 4000:8080

volumes:
  db_volume:
      